name: e_commerce
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.3.1
  shelf_router: ^1.1.0
  shelf_static: ^1.1.0
  file_picker: ^5.2.2
  path_provider: ^2.0.11
  permission_handler: ^11.3.0
  dio: ^5.7.0
  http: ^1.2.0
  image_picker: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/categories/
  fonts:
    - family: DM Sans
      fonts:
        - asset: fonts/DMSans_24pt-Regular.ttf

